### ISSUE TITLE
Tab bar is fully transparent since the latest FF release.

### ISSUE THREAD

**Issue by manthanf1** [rockofox/firefox-minima#10]
![Screenshot](https://github.com/rockofox/firefox-minima/assets/65068524/354aa186-3995-4d49-80df-90c530094473)

![Screenshot-with-navbar-focus](https://github.com/rockofox/firefox-minima/assets/65068524/4a696982-c15b-445c-a91f-4b226a1e6b73)

I tried using `opacity:1 !important` on some .tabbrowser-tab selectors, but to no success.

Any pointers would be appreciated.

**Comment by manthanf1** [comment]
The workaround that worked for me

```css
#titlebar {
	background-color: #solid-color !important;
}
```
